
services:

  # 1. PostgreSQL container
  db:
    image: postgres:16
    container_name: Alert_bot_db
    environment:
      # Read credentials from .env
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist DB data across restarts
    restart: always

  # 2. Redis container
  redis:
    image: redis:alpine
    container_name: Alert_bot_redis
    ports:
      - "${REDIS_PORT}:6379" # 80 for outside, 6379 inside container
    restart: always
  # 3. app 
  app: 
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: Alert_bot_app
    env_file: .env # Load environment variables from .env
    depends_on:
      - db
      - redis
    restart: always
  
  

# Define a volume for DB data persistence
volumes:
  pgdata:

# yaml.cheker online: https://yamlchecker.com/
